inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
  TargetRubyVersion: 2.0

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: false
