require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - gemfiles/*
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 2.7

Gemspec/RequireMFA:
  Exclude:
    - 'permanent_records.gemspec'

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: false
