require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
    - gemfiles/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: false
