name: Ruby Gem

on:
  push:
    branches:
      - master

jobs:
  build:
    name: gem publishing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Install bundle
      run: bundle
    - name: Run rubocop
      run: bundle exec rubocop

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        bin/gempush-if-changed
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
