name: Tests

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0.0'
          - '3.3.0'
        rails:
          - '5.0.7.2'
          - '5.1.7'
          - '5.2.3'
          - '6.1.7.6'
          - '7.1.2'
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y libsqlite3-dev
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - run: gem install bundler && bundle && bundle exec rake 
        env:
          AR_TEST_VERSION: ${{ matrix.rails }}

